# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Check Code Lint

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: lts/*
        cache: 'yarn'

    - name: Install Dependencies
      run: yarn install
        
    - name: Check Lint
      run: yarn lint
  
  test:
    name: Test Code

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, lts/*]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install Dependencies
      run: yarn install
    
    - name: Test
      run: yarn test

  build:
    name: Check Build Process
    needs: test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, lts/*]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install Dependencies
      run: yarn install
   
    - name: Build
      run: yarn build
